apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 for "password"
  MYSQL_DATABASE: d29yZHByZXNz       # base64 for "wordpress"
  MYSQL_USER: dXNlcg==               # base64 for "user"
  MYSQL_PASSWORD: c2VjcmV0           # base64 for "secret"
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==   # base64 for "mysql-service"
